### ISSUE TITLE
Searching by postcode or location results in white screen

### ISSUE THREAD

**Issue by davidscotson** [LibrariesHacked/librarymap#31]
In various browsers I just tried on Mac OS X (Chrome, Safari, Firefox) the library search looks like it's working then suddently the screen goes white.

The JS Console says:

    2.529a5dff.chunk.js:1 TypeError: Cannot read property 'map' of null
    at Object.render (main.829bf526.chunk.js:1)
    at n.value (2.529a5dff.chunk.js:1)
    at n.value (2.529a5dff.chunk.js:1)
    at qa (2.529a5dff.chunk.js:1)
    at Ua (2.529a5dff.chunk.js:1)
    at ws (2.529a5dff.chunk.js:1)
    at vl (2.529a5dff.chunk.js:1)
    at ml (2.529a5dff.chunk.js:1)
    at sl (2.529a5dff.chunk.js:1)
    at 2.529a5dff.chunk.js:1

This also happens if you choose a service from the dropdown list. Browsing the map rather than searching all seems to be working fine.

**Comment by DaveBathnes** [comment]
Thanks for raising this!

I suspect something went down - possibly the postcode API but more likely the mobile libraries API. At the moment I can't recreate the issue, but I'll test to simulate that scenario and code around it.

**Comment by davidscotson** [comment]
This was still happening for me, and after working my way down the alphabetical list of services, to see which worked and which showed the bug it seems that it doesn't affect England, but Scottish and Welsh regions show the issue. Possibly something do do with different data sources for those areas?

**Comment by davidscotson** [comment]
Slighty different error in the JS Console:

    TypeError: can't access property "map", t.unstaffed is null
    render Libraries.js:213
    value m-table-cell.js:111
    value m-table-cell.js:205
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6

**Comment by DaveBathnes** [comment]
Thanks!

My fault - this issue wasn't even in the current version of the code - I'm obviously just running on a slightly outdated build. That'll teach me now to have proper continuous integration set up. 

It was a problem with opening hours, which I did a little work on. The data source for Wales and Scotland didn't have opening hours with them - though it should just display 'Opening hours unknown'. 

Should be fixed in production now!
